[[redirects]]
  from = "/about"
  to = "/about"

[[redirects]]
  from = "/projects"
  to = "/projects"

[[redirects]]
  from = "/projects/*"
  to = "/projects/:projectPath"

[[redirects]]
  from = "/articles"
  to = "articles"

[[redirects]]
  from = "/articles/*"
  to = "/articles/:articlePath"

[[redirects]]
  from = "/about"
  to = "about"